version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SCHDLSTR_DATABASE_PATH=/app/data/scheduler.db
      - SCHDLSTR_RELAYS_PATH=/app/data/relays.json
      - SCHDLSTR_LOG_LEVEL=INFO
    volumes:
      - backend_data:/app/data
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - backend
    environment:
      - SCHDLSTR_DATABASE_PATH=/app/data/scheduler.db
      - SCHDLSTR_RELAYS_PATH=/app/data/relays.json
      - SCHDLSTR_LOG_LEVEL=INFO
    volumes:
      - backend_data:/app/data
    command: ["python", "publisher.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"

volumes:
  backend_data:
